### PR TITLE
Update to 1.8.1

### PR DESCRIPTION
**Pull request by untoldwind**
Made some adjustments for 1.8.1

Probably due to the Unity update it is not full functional. It can load/install a plugin, but reloading a new version (the main reason for this) does only works with a trick.

Here the issue:
* The new version of the DLL is loaded as byte[] correctly (thats why I added the MD5 to ensure)
* ... but Assembly.Load() of that byte[] still results in the Assembly of the original version. I think this has something to do with shadow copying or the likes.

So here is the trick:
* Instead of creating a "MyPlugin.dll" I create a "MyPlugin<timestamp>.dll" (e.g. with `msbuild \Property:AssemblyName=...`)
* Then I sym-link "MyPlugin<timestamp>.dll" -> "MyPlugin.dll" and let KSP load that one.
* Since the name of the assembly has changed Assembly.Load() now results in the new version

This is of course quite cumbersome and probably clutters up memory pretty fast. I suppose for a correct solution we have to wait until the AssemblyLoadContext become available in Unity.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
What do you mean by "reloading a new one"?
It appears to me that you are trying to replace the DLL on the fly.  Is that correct?

**Comment by untoldwind** [comment]
Yes, the basic idea is to read a new version of the plugin's DLL, destroy all classes/MonoBehaviors of the previous version and bootstrap everything with the new version again.

Down below the new version is loaded as byte[] and then passed forward to Assembly.Load
In the previous Unity runtime this was working quite well, the current runtime though just ignores the new byte[] if it thinks that the assembly is already loaded. The only way I found to circumvent this is to change the assembly name with each version (as described with the symlink trick).

So overall this Plugin is still somewhat working/useful with 1.8.1

**Comment by linuxgurugamer** [comment]
Sorry, I can't accept this PR.  I can't imagine any player who would be doing this.  When a player has a problem, they would install the dll and restart the game.  Nobody recommends replacing a dll at runtime in KSP.

**Comment by untoldwind** [comment]
Err ... ok ... no offense and such, but:

This Mod/Repository `KramaxPluginReload` is explicitly addressed to Mod-Developers who *want* to reload their development DLL on the fly without the need to restart the game. Its pretty much the first sentence/paragraph of the README.

All I did in this RP was to make some basic adjustments for 1.8.1 that where just missing. The core of the reloading stuff is untouched.

... just to clarify things. Won't bugger you any more.

**Comment by linuxgurugamer** [comment]
As you can tell, I don't do much with this mod.
would you like to adopt it?

**Comment by untoldwind** [comment]
Well, I do most of my development on Linux so I don't know if I can offer much help with windows. But otherwise I think I could do that.

**Pull request closed without merging**
